#!/usr/bin/env python
#
# Copyright 2017 Wahana Mandiri Syadratama .PT
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""Simplified CTI (Computer telephony integration)."""

# import const

CR_UNRECOGNIZED = 404
CR_INVALID_STRUCT = 405
CR_INVALID_PARAM = 406
CR_INVALID_SIZE = 407
CR_INVALID_CONN = 408
CM_KILL_DEVICE = 100
CM_RUN_DEVICE = 101
CM_RECONFIGURE = 102
CM_SET_TRACE_LEVEL = 108
CM_USER_CTI_LINKUP = 120
CM_CTI_USER_LOGIN = 121
CM_CTI_ADD_USER = 122
CM_CTI_DELETE_USER = 123
CM_CTI_SHUTDOWN_USER = 124
CM_DEV_MAKE_CALL = 200
CM_DEV_HANGUP_CALL = 201
CM_DEV_HOLD_CALL = 202
CM_DEV_RETRIEVE_CALL = 204
CM_DEV_ANSWER_CALL = 205
CM_DEV_TRANSFER_CALL = 206
CM_DEV_CONFERENCE_CALL = 207
CM_DEV_ROUTE_CALL = 208
CM_DEV_AG_READY = 212
CM_DEV_AG_AUX = 213
CM_DEV_AG_LOGIN = 210
CM_DEV_AG_LOGOUT = 211
EV_DEV_DIALING = 220
EV_DEV_BUSY = 221
EV_DEV_IDLE = 222
EV_DEV_DEST_BUSY = 223
EV_DEV_DEST_NOANSWER = 224
EV_DEV_HELD = 225
EV_DEV_RETRIEVED = 226
EV_DEV_TRANSFERRED = 227
EV_DEV_ESTABLISHED = 228
EV_DEV_INITIATED = 229
EV_DEV_DELIVERED = 230
EV_DEV_ORIGINATED = 231
EV_DEV_CON_CLEAR = 232
EV_DEV_CONFERENCED = 233
EV_DEV_DIVERTED = 234
EV_DEV_FAILED = 235
EV_DEV_AGENT_LOGON = 236
EV_DEV_AGENT_LOGOFF = 237
EV_DEV_QUEUED = 238
EV_DEV_CALL_OFFER = 239
EV_DEV_ROUTE_REQUEST = 240
EV_DEV_MONITOREND = 241
EV_DEV_MONITORFAIL = 242
EV_DEV_CALL_CLEAR = 243
CM_FAIL = 199
CM_FAIL_DEV_DOWN = 191
CM_FAIL_NOT_GRANTED = 192
CM_FAIL_LOGIN_VERIFY = 193
CM_FAIL_USER_ADD_MAX = 194
CM_FAIL_USER_ADD_EXIST =195
CM_FAIL_RUN_DEVICE = 196
CM_FAIL_SHUTDOWN_USER = 197
AD_READY = 800
AD_ERROR = 801
EV_DEV_OUTGOING = 250
EV_DEV_INCOMING = 251
EV_DEV_STATUS	= 252
